In [20]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df["label"] = iris.target  # Adding the 'label' column


# Function to apply Gaussian noise to a DataFrame with labels
def apply_gaussian_noise(dataframe, noise_factor=0.1):
    # Make a copy of the original DataFrame
    noisy_data = dataframe.copy()
    features = noisy_data.drop(columns=["label"])
    noise = np.random.normal(loc=0, scale=noise_factor, size=features.shape)
    # Apply the noise to the copy
    noisy_data.iloc[:, :-1] += noise
    return noisy_data


# List of scales for augmentation
scales = [0.05, 0.1, 0.15, 0.2, 0.25]

# Generate augmented data
augmented_data = [apply_gaussian_noise(iris_df, noise_factor=scale) for scale in scales]

# Concatenate the list of DataFrames into a single DataFrame
augmented_df = pd.concat(augmented_data, ignore_index=True)

# Display the augmented DataFrame
print("Augmented Iris Dataset:")
print(augmented_df.head())

Augmented Iris Dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0           5.084745          3.542795           1.423897          0.251245
1           4.939707          2.950555           1.403218          0.252681
2           4.675016          3.221723           1.302516          0.157799
3           4.585817          3.062730           1.558837          0.202905
4           4.995597          3.563572           1.376953          0.144687

   label
0      0
1      0
2      0
3      0
4      0

In [22]:
len(iris_df)

150

In [23]:
augmented_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.084745,3.542795,1.423897,0.251245,0
1,4.939707,2.950555,1.403218,0.252681,0
2,4.675016,3.221723,1.302516,0.157799,0
3,4.585817,3.062730,1.558837,0.202905,0
4,4.995597,3.563572,1.376953,0.144687,0
...,...,...,...,...,...
745,6.607468,3.132194,4.951847,2.252720,2
746,6.200822,2.243449,4.999222,1.846862,2
747,6.181164,3.057337,5.204546,2.390146,2
748,6.763404,3.625104,5.224773,2.121359,2
749,5.882010,2.888668,5.489166,1.893839,2